services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shopping
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./script/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - services_network
    restart: always

  postgres:
    image: postgres:15
    container_name: postgressql
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - services_network
    restart: always

volumes:
  mysql_data:
    driver: local
  postgres_data:
    driver: local

networks:
  services_network:
    driver: bridge
